config/routes.rb
App1::Application.routes.draw do
  
  resources :users
  root :to => "pages#home"
  match '/contact', :to=>'pages#contact'
  match '/about', :to=>'pages#about'
  match '/help', :to=>'pages#help'
  match '/signup', :to=>'users#new'
  













end

app/models/user.rb
# == Schema Information
# Schema version: 20110529092007
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#

class User < ActiveRecord::Base
   attr_accessor   :password
   attr_accessible :name,:email,:password,:password_confirmation
   
   email_regexp = /\A[_a-zA-Z+\-\.0-9]+@[a-z0-9\-.]+\.[a-z]+\z/i

   validates :name, #:presence => true,
                    :length   => {:maximum=>50,:minimum=>1}
   validates :email,:presence => true,
                    :format   => {:with=>email_regexp},
                    :uniqueness=> {:case_sensitive=>false}
   validates :password, :presence => true,
                        :confirmation=>true,
                        :length =>{#:maximum=>20,:minimum=>6,
                                 :within=>6..20}
   #callback methods 
   before_save :encrypt_password  #---> method 
  def has_password?(sub_pwd)
   encrypted_password==encrypt(sub_pwd)
  end

class << self  #User's class
 
  def authenticate(email,pwd)
     user=find_by_email(email)
     return nil   if user.nil?
     return user  if user.has_password?(pwd)
   end

end

private
def encrypt_password
 self.salt= make_salt if new_record?
 self.encrypted_password=encrypt(self.password)

end
def encrypt(string)
secure_hash("#{salt}--#{string}")
end
def make_salt
secure_hash("#{Time.now.utc}--#{password}")
end
def secure_hash(string)
Digest::SHA2.hexdigest(string)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
@title="Home"  
end

  def contact
@title="Contact"
end
def about
@title="About"
  end
def about
@title="Help"
  end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
  
  def  show
    #@user=User.find_by_email("sukesh@futurenow.biz")
     #@user=User.find("3")
     @user=User.find(params[:id])
     @title=@user.name
  end
  def new
  	@title="Sign up"
  end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper

# Return a title on a per-page basis.
 def title
  base_title='Ruby on Rails Tutorial Sample App'
  if @title.nil?
   base_title
  else
   "#{base_title}|#{@title}"
   end
  end
  def logo
  	image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
 end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user,options={:size=>100})
     gravatar_image_tag(user.email.downcase,:alt=>user.name,
                                            :class=>'gravatar',
                                            :gravatar=>options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<%= link_to logo ,root_path
 %>
<nav class="round">
<ul>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<li><%= link_to "Sign in", '#' %></li>
</ul>
</nav>
</header>

app/views/layouts/_stylesheet.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%=stylesheet_link_tag 'blueprint/screen', :media=>'screen' %>
<%=stylesheet_link_tag 'blueprint/print', :media=>'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE>
<html>
<head>
<title><%=@title%></title>
<%= csrf_meta_tag %>
<%= render 'layouts/stylesheet' %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<section class="round">
<%= yield %>
</section>
<%= render 'layouts/footer' %><br><br><br><br><br>
<b><div align="center"><u>Debug</u><font color="red">
<%= debug(params) if !Rails.env.develpment? %>
</b></font>
</div>
</div>
</body>
</html>

app/views/pages/about.html.erb

<h1>About Us</h1>
<p>Know about us at  <a href ="http://railstutorial.org/">Ruby on Rails</a>Sample Application.
</p>


app/views/pages/contact.html.erb

<h1>Contact App</h1>
<p>This is the contact Ruby at <a href ="http://railstutorial.org/feedback">Feedback page</a>Sample Application.
</p>


app/views/pages/help.html.erb

<h1>Help</h1>
<p>get Help on <a href ="http://railstutorial.org/">Ruby on Rails Tutorial</a>Sample Application.
</p>

app/views/pages/home.html.erb

<h1>Sample App</h1>
<p>This is the home Page for the <a href ="http://railstutorial.org/">Ruby on Rails Tutorial</a>Sample Application.
</p>
<%= link_to "Sign up now!",signup_path,:class=>"signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Profile information" >
 <tr>
   <td class="main">
    <h1><b>
    <%=gravatar_for @user%>
    <font color="#8IRUH87"><%=@user.name%>
    <br></font>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<font     color="#8IRUH87"><%=@user.email%></font>
</h1></b>
</td>
<td class="sidebar round"><font color="#9885">
 <strong>Name:&nbsp&nbsp</strong><%= @user.name%><br />
 <strong>URL:&nbsp&nbsp</strong><%=link_to user_path(@user),
 user_path(@user)%>	
</td>
</tr></font>
</table>